name: Main
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.x"
      - name: Install dependencies
        working-directory: ./backEnd/
        run: npm i
  buildFront:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.x"
      - name: Install dependencies
        working-directory: ./frontEnd/
        run: npm i
      - name: build static website
        working-directory: ./frontEnd/
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          appdir: ./backEnd/
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "loginformsbackend"
          heroku_email: "alireza_esi14@yahoo.com"
  deployFront:
    runs-on: ubuntu-latest
    needs: [buildFront]
    steps:
    - name: Configure GitHub Pages
      uses: actions/configure-pages@v2.1.0
      with:
        # Optional file path to static site generator configuration file
        generator_config_file: ./frontEnd/dist/

