name: Main
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.x"
      - name: Install dependencies
        working-directory: ./backEnd/
        run: npm i
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          appdir: ./backEnd/
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "loginformsbackend"
          heroku_email: "alireza_esi14@yahoo.com"
  deployFront:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "16.x"
    - name: Install dependencies
      working-directory: ./frontEnd/
      run: npm i
    - name: build static website
      working-directory: ./frontEnd/
      run: npm run build
    - name: check if dist exist
      working-directory: ./frontEnd/
      run: ls
    - name: Deploy to GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: JamesIves/github-pages-deploy-action@13046b614c663b56cba4dda3f30b9736a748b80d
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        # The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.
        folder: ./frontEnd/dist


